### ISSUE TITLE
Date Reminding Layout 

### ISSUE THREAD

**Issue by Davouro** [floriankorstanje/ByeBot#2]
Change from:
$reminde me add [date] date [reminder]
to
$reminde me add date [date] [reminder]

**Comment by floriankorstanje** [comment]
That would also change the other time units from `reminders add [days/hours/minutes] [time] [reminder]`

**Comment by Davouro** [comment]
Would it work if u just had [date] and didn't have to specify

**Comment by floriankorstanje** [comment]
No, because then it would get the first word in [reason] and try to parse that to `days`, `hours` or `minutes`
